# Generated by Django 4.1.3 on 2022-11-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'Coupon', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AddField(
            model_name='coupons',
            name='minimum',
            field=models.IntegerField(default=500),
        ),
    ]
