# Generated by Django 4.1.3 on 2022-11-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='stock',
            new_name='amount',
        ),
    ]
