# Generated by Django 4.1.3 on 2022-11-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_coupon_remove_shopcart_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
