# Generated by Django 4.1.3 on 2022-11-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catparent',
            field=models.ForeignKey(blank=True, limit_choices_to={'catparent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
    ]
