# Generated by Django 4.1.3 on 2022-11-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_featured_product_new_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='img',
            new_name='image',
        ),
    ]
