# Generated by Django 4.1.3 on 2022-11-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_img_images_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='product',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
