# Generated by Django 4.1.3 on 2022-11-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_name_color_color_size_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
    ]
