# Generated by Django 4.1.3 on 2022-11-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='default_img',
        ),
    ]
