# Generated by Django 4.1.3 on 2022-11-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
