# Generated by Django 4.1.3 on 2022-11-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_alter_product_featured_alter_product_flash_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='default_price',
        ),
    ]
